export const tripData = [
  {
    id: 1,
    tripId: "TRIP001",
    date: "2025-04-10",
    customer: "John Doe",
    driver: "Alex Smith",
    tripType: "One Way",
    tripCost: 50.0,
    couponDiscount: 5.0,
    additionalFee: 2.5,
    totalCost: 47.5,
    adminCommission: 10.0,
    paymentStatus: "Paid",
    tripStatus: "Completed",
  },
  {
    id: 2,
    tripId: "TRIP002",
    date: "2025-04-11",
    customer: "Jane Watson",
    driver: "Chris Johnson",
    tripType: "Round Trip",
    tripCost: 120.0,
    couponDiscount: 10.0,
    additionalFee: 5.0,
    totalCost: 115.0,
    adminCommission: 20.0,
    paymentStatus: "Unpaid",
    tripStatus: "Pending",
  },
  {
    id: 3,
    tripId: "TRIP003",
    date: "2025-04-12",
    customer: "Michael Lee",
    driver: "Sarah Brown",
    tripType: "Hourly",
    tripCost: 75.0,
    couponDiscount: 0,
    additionalFee: 0,
    totalCost: 75.0,
    adminCommission: 15.0,
    paymentStatus: "Paid",
    tripStatus: "Ongoing",
  },
  {
    id: 4,
    tripId: "TRIP004",
    date: "2025-04-13",
    customer: "Emily Davis",
    driver: "David Miller",
    tripType: "One Way",
    tripCost: 65.0,
    couponDiscount: 5.0,
    additionalFee: 3.0,
    totalCost: 63.0,
    adminCommission: 12.0,
    paymentStatus: "Paid",
    tripStatus: "Cancelled",
  },
];
